config/routes.rb
Rails.application.routes.draw do
  get 'expenses_senders/new'
  get 'expenses_senders/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'expenses#index'
  resources :expenses, except: :show

  resources :users do
    resource :filter, only: [:update, :reset] do
      put :reset
    end

    resource :expenses_sender, only: [:update, :edit]
    resource :expenses_print, only: [:print] do
      get :print
    end
  end
end

app/models/expenses_sender.rb
class ExpensesSender < ApplicationRecord
  belongs_to :user

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
end

app/controllers/expenses_senders_controller.rb
class ExpensesSendersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expenses_sender, only: [:edit, :update]

  def edit
    @expenses_ids = params[:expenses]
    respond_to do |f|
      f.html
      f.js { render template: 'expenses_senders/edit' }
    end
  end

  def update
    @expenses_sender = ExpensesSenderService.update(@expenses_sender, expenses_sender_params, expenses_ids)
    respond_to do |f|
      if @expenses_sender.errors.empty? && verify_recaptcha(model: @expenses_sender)
        SenderToEmailWorker.perform_async(@expenses_sender.email, current_user.id, expenses_ids)
        flash.now[:notice] = "Expenses pages successful deliver to #{@expenses_sender.email}"
        f.js { render template: 'expenses_senders/update' }
      else
        f.js { render template: 'expenses_senders/update_errors' }
      end
    end
  end

  private

  def set_expenses_sender
    @expenses_sender = current_user.expenses_sender
  end

  def expenses_sender_params
    params.require(:expenses_sender).permit(:email)
  end

  def expenses_ids
    Filter.check_expenses(@expenses_sender.user.id).ids
  end
end

app/helpers/expenses_senders_helper.rb
module ExpensesSendersHelper
end

app/views/expenses_senders/_form.html.erb
<%= form_for(@expenses_sender, local: true, remote: true, url: user_expenses_sender_path(current_user), method: :put, validate: true) do |f| %>
  <div class="modal fade" id="senderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-mailer" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Expenses mailer</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="edit.js.coffee">
            <div class="form-group row">
              <%= f.label :email, 'email', class: 'col-xs-3 col-form-label mr-2' %>
              <div class="col-md-9">
                <%= f.text_field :email, value: current_user.expenses_sender.email, class: 'form-control' %>
              </div>
              <div class="col-xs-3 recaptcha">
                <%= recaptcha_tags %>
              </div>
            </div>

            <% if @expenses_sender.errors[:base].present? %>
                <%= label_tag :base, @expenses_sender.errors[:base].last, class: 'message center' %>
            <% end %>

          </form>
        </div>
        <div class="modal-footer">
          <%= hidden_field_tag 'expenses', @expenses_ids %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit 'send', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>


<% end %>