config/routes.rb
Rails.application.routes.draw do
  get 'expenses_senders/new'
  get 'expenses_senders/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'expenses#index'
  resources :expenses, except: :show

  resources :users do
    resource :filter, only: [:update, :reset] do
      put :reset
    end

    resource :expenses_sender, only: [:update, :edit]
    resource :expenses_print, only: [:print] do
      get :print
    end
  end
end

app/models/filter.rb
require_relative '../../lib/date_query_calculator.rb'

class Filter < ApplicationRecord
  extend DateQueryCalculator
  belongs_to :user
  has_one :currency, as: :currencyable
  accepts_nested_attributes_for :currency, update_only: true

  JSON_SCHEMA = "#{Rails.root}/app/models/schemas/filter/data.json"

  DEFAULT_PARAMS = {
      data: {
          rubric_names: '',
          amount: { start: 0, finish: '' },
          duration: date_to_s(Date.today - 29.day..Date.today),
      },
      currency_attributes: { name: 0 }
  }

  before_create :build_currency
  before_save :build_duration

  validates :data, presence: true, json: { schema: JSON_SCHEMA }
  validates :currency, presence: true
  validate :verify_amount_finish
  validate :verify_date_range

  def self.check_expenses(user_id)
    current_filter = User.find(user_id).filter
    data_filter = current_filter.data
    default_query = "user_id = #{user_id}"
    Expense.order(created_at: :desc, updated_at: :desc, id: :desc).
            where("#{default_query}
                   #{rubrics_query(data_filter)}
                   #{amount_range_query(data_filter)}
                   #{duration_query(Filter.check_duration_range(data_filter['duration']))}")
  end

  def self.filterable?(expense)
    current_filter = User.find(expense['user_id']).filter
    data_filter = current_filter.data
    query_expense_id = "id = #{expense['id']}"
    resp = Expense.where("#{query_expense_id}
                  #{rubrics_query(data_filter)}
                  #{amount_range_query(data_filter)}
                  #{duration_query(Filter.check_duration_range(data_filter['duration']))}")
    true ? resp.present? : false
  end

  private

  def self.rubrics_query(current_user_filters)
    if current_user_filters['rubric_names'].present?
      array_for_sql = current_user_filters['rubric_names'].split(',').map { |x| "'#{x}'" }.join(', ')
      array_for_sql.insert(0, '(')
      array_for_sql += ')'
      " AND expense_type IN #{array_for_sql}"
    else
      ''
    end
  end

  def self.amount_range_query(current_user_filters)
    if current_user_filters['amount']['finish'].present?
      " AND amount >= '#{current_user_filters['amount']['start'].to_f}'
        AND amount <= '#{current_user_filters['amount']['finish']}'"
    else
      " AND amount >= '#{current_user_filters['amount']['start'].to_f}'"
    end
  end

  def self.duration_query(filter)
    " AND created_at >= '#{filter.first}'
      AND created_at <= '#{filter.last}'"
  end

  def build_duration
    data[:duration] = Filter.check_duration_type(data['duration'], '-')
  end

  def build_currency
    self.currency = Currency.new(currencyable_type: self.class)
  end

  def verify_amount_finish
    return true if data['amount']['finish'].blank?
    amount_start = data['amount']['start']
    amount_finish = data['amount']['finish'].to_f
    self.errors.add(:data, 'invalid amount_range') if amount_finish < amount_start
  end

  def verify_date_range
    current_date = Filter.check_duration_type(data['duration'], '-')

    if current_date.is_a?(Hash)
      verify_custom_range(current_date)
    elsif current_date.is_a?(Symbol)
      verify_given_string_date(current_date)
    else
      self.errors.add(:data, 'invalid date range')
    end
  end

  def verify_custom_range(current_date)
    date_start = Date.today - 100.year
    date_end = Date.today.end_of_day
    date_range = date_start...date_end

    begin
      duration_start = current_date[:custom_range].first
      duration_end = current_date[:custom_range].end

      if duration_start > duration_end ||
          date_range.exclude?(duration_start) ||
          date_range.exclude?(duration_end.beginning_of_day)

        self.errors.add(:data, 'invalid date range')
      end
    rescue
      self.errors.add(:data, 'invalid date range')
    end
  end

  def verify_given_string_date(current_date)
    self.errors.add(:data, 'invalid date range') if DateQueryCalculator::DATE_RANGES.keys.exclude?(current_date)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_filter, only: [:update, :reset]

  def update
    FilterService.update(@filter, filter_params)

    respond_to do |format|
      if @filter.errors.empty?
        format.html { redirect_to root_path, notice: 'Filters successfully updated.' }
      else
        format.html { redirect_to root_path, alert: 'Filters have unless values.' }
      end
    end
  end

  def reset
    respond_to do |format|
      if @filter.update(Filter::DEFAULT_PARAMS)
        format.html { redirect_to root_path, notice: 'Filters successfully reset.' }
      else
        format.html { redirect_to root_path, alert: 'Filters have unless values' }
      end
    end
  end

  private

  def filter_params
    params[:filter][:data][:amount][:start] = params[:filter][:data][:amount][:start].to_f
    params.require(:filter).permit(data: {}, currency_attributes: [:name])
  end

  def set_filter
    @filter = User.find(current_user.id).filter
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
  def round_amount(amount)
    amount.present? ? '%.2f' % amount : ''
  end

  class CurrencyNames
    attr_reader :names, :current_name

    def initialize(current_name)
      @names = Currency.names.dup
      @names.delete(current_name)
      @names = @names.map(&:first)
      @current_name = current_name
    end
  end
end

app/views/filters/_filter.html.erb
<div class="col-lg-4 filters-bar">
  <div class="well sidebar-nav">
    <h3><%= t(:expenses_filters) %></h3>
    <div class="link-tags">
      <%= form_for(current_user, url: user_filter_path(current_user), method: :put) do %>
        <%= hidden_field_tag 'filter[data[duration]]' %>

        <div id="reportrange" class="calendar form-control">
          <i class="fa fa-calendar"></i>&nbsp;
          <span id="filter_date_duration"></span> <i class="fa fa-caret-down"></i>
        </div>
        <br>

        <%= label_tag 'filter[data[rubric_names]]', 'Rubrics' %>
        <%= text_field_tag 'filter[data[rubric_names]]', current_user.filter.data['rubric_name'], class: 'form-control filter-rubrics', placeholder: 'Rubric1,Rubric2', value: current_user.filter.data['rubric_names'] %>
            <br><br>

            <%= label_tag 'filter[data[amount][start]]', 'Amount range' %>
            <span> >= </span>
            <%= text_field_tag 'filter[data[amount][start]]', round_amount(current_user.filter.data['amount']['start']), class: 'form-control amount-range', placeholder: '0.00' %>
            <span> <= </span>
            <%= text_field_tag 'filter[data[amount][finish]]', round_amount(current_user.filter.data['amount']['finish']), placeholder: '∞', class: 'form-control amount-range placeholder_center' %>

        <br><br>

        <%= label_tag('filter[currency_attributes[name]]', 'Currency convert') %>
        <% range = FiltersHelper::CurrencyNames.new(current_user.filter.currency.name) %>
        <%= select_tag('filter[currency_attributes[name]]', options_for_select(range.names), prompt: range.current_name, class: 'form-control currency-convert') %>
        <br>

        <div class="row">
            <%= button_to user_filter_path(current_user), method: :put, class: 'btn-alignment button-apply' do %>
              <i class="fa fa-check apply" aria-hidden="true">Apply</i>
            <% end %>

            <%= link_to reset_user_filter_path(current_user), class: 'link-reset', method: :put do %>
              <i class="fa fa-refresh link-alignment reset" aria-hidden="true">&nbsp;Reset</i>
            <% end %>
        </div>

      <% end %>
      <br>

    </div>
  </div><!--/.well -->
</div><!--/span-->