config/routes.rb
Rails.application.routes.draw do
  get 'expenses_senders/new'
  get 'expenses_senders/create'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'expenses#index'
  resources :expenses, except: :show

  resources :users do
    resource :filter, only: [:update, :reset] do
      put :reset
    end

    resource :expenses_sender, only: [:update, :edit]
    resource :expenses_print, only: [:print] do
      get :print
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expenses, except: [:new, :edit]
  before_action :set_currency_convert, only: :index
  before_action :set_expense, only: [:edit, :update, :destroy]
  before_action :set_filter, only: :index

  # GET /expenses
  # GET /expenses.json
  def index
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    respond_to do |format|
      format.html
      format.js { render template: 'expenses/modal' }
    end
  end

  # GET /expenses/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js { render template: 'expenses/modal' }
    end
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = ExpenseService.create(expense_params, current_user.id)
    respond_to do |format|
      if @expense.errors.empty?
        format.html { redirect_to root_path, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
        format.js { flash.now[:notice] = 'Expense was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
        format.js { render template: 'expenses/modal_errors' }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @before_expense = @expense.attributes
    @before_expense['currency'] = @expense.currency.attributes
    @before_position = @expenses.page(params[:page]).find_index { |exp| exp.id == @expense.id }
    ExpenseService.update(@expense, expense_params)

    respond_to do |format|
      if @expense.errors.empty?
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
        format.js { flash.now.notice = 'Expense was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
        format.js { render template: 'expenses/modal_errors' }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      flash.now.notice = 'Expense was successfully destroyed.'
      format.html { redirect_to root_path, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
      format.js { flash.now.notice = 'Expense was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_filter
    filter = Filter.find { |f| f.user_id == current_user.id }.data['duration']
    @filter = Filter.check_duration_range(filter)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :type_amount, :expense_type, :created_at, currency_attributes: [:name])
  end

  def set_expenses
    @expenses = Filter.check_expenses(current_user.id).page(params[:page])
    @expenses_before = @expenses.dup.to_a
  end

  def set_currency_convert
    if params[:page].nil?
      current_user.currency_convert.update_bank(@expenses, current_user.filter.currency.name)
      current_user.currency_convert.transfer_transit
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  # receive @expenses page before and initialize @expenses after
  # compares their expenses page and calculate expense with position for create and for destroy
  class DisplacementCalculator
    attr_reader :for_adds, :for_removes

    def initialize(expenses_before, expenses_after)
      @expenses_before = expenses_before
      @expenses_after = expenses_after
      @expenses_create = expenses_after - expenses_before
      @expenses_destroy = expenses_before - expenses_after
    end

    def add_for_creates
      @for_adds ||= [] # [[position, expense]...]
      expenses_create_ids = @expenses_create.map(&:id)
      @expenses_after.each_with_index { |exp, index| @for_adds << {position: index, exp: exp} if expenses_create_ids.include?(exp.id) }
    end

    def add_for_removes
      @for_removes ||= []
      @for_removes |= @expenses_destroy.map(&:id)
    end

    def add_for_edit_per_page(expense)
      expense_index_before = @expenses_before.find_index { |exp| exp.id == expense.id }
      expense_index_after = @expenses_after.find_index { |exp| exp.id == expense.id }

      if expense_index_before == expense_index_after
        { position: expense_index_before, remove_position: false }
      elsif expense_index_after.present?
        { position: expense_index_after, remove_position: expense_index_before }
      else
        false
      end
    end
  end
end

app/views/expenses/_for_print.html.erb
<table class="table table-striped d-print-table">
  <thead class="thead-dark">
  <tr>
    <th><%= t(:expense_heading) %></th>
    <th><%= t(:expense_amount) %></th>
    <th><%= t(:expense_type) %></th>
    <th><%= t(:created_at) %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody id="search_list">
  <% expenses.each_with_index do |expense| %>
    <tr>
      <td><%= expense.name %></td>
      <td><%= expense.current_currency %></td>
      <td><%= expense.expense_type %></td>
      <td><%= expense.created_at.strftime('%d.%m.%Y') %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/expenses/_form.html.erb
<script>
    $(function () {
        <% if @expense.created_at.nil? %>
        var start2 = moment();
        <% else %>
        var start2 = moment("<%= @expense.created_at.to_date.to_s %>");
        <% end %>

        function cb(start2) {
            $('#expense_date span').html(start2.format('MMMM D, YYYY'));
        }

        $('#expense_date').daterangepicker({
            singleDatePicker: true,
            startDate: start2,
            maxDate: moment(),
            showDropdowns: true,
            locale: {
                format: 'MMMM D, YYYY'
            }
//                          minYear: 2000,
//                          maxYear: 2018
        }, cb);

        cb(start2);
    });

    $('#modal-sub').click(function() {
        $('#expense_created_at').val($('#date').html());
    });

    $("label[for = 'expense_created_at']").click(function () {
        $("#expense_date").click();
    });

    $('#modal-sub').enableClientSideValidations();


</script>

<%= form_for(@expense, local: true, remote: true) do |form| %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Expense <%= modal_name %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="actions">
            <form action="create.js.coffee">

              <div class="form-group row">
                <%= form.label :name, class: 'col-xs-3 col-form-label mr-2' %>
                <div class="col-xs-9">
                  <%= form.text_field :name, class: 'form-control', maxlength: Expense::MAX_LENGTH %>
                </div>
              </div>

              <div class="form-group row">
                  <%= form.label :created_at, class: 'col-xs-3 col-form-label mr-2' %>
                <div class="col-xs-9">
                  <div id="expense_date" class="calendar form-control">
                    <i class="fa fa-calendar"></i>&nbsp;
                    <span id="date"></span> <i class="fa fa-caret-down"></i>
                  </div>
                </div>

                <% if @expense.errors[:created_at].present? %>
                  <label for="calibration" class="col-xs-3 col-form-label mr-2 visibility-calibration">q</label>
                <% end %>
                <div class="col-xs-9">
                  <%= form.text_field :created_at, class: 'js-calibration', id: 'expense_created_at' %>
                </div>
              </div>

              <div class="form-group row">
                <%= form.label :amount, class: 'col-xs-3 col-form-label mr-2' %>
                <div class="col-xs-9">
                  <%= form.text_field :amount, value: '%.2f' % @expense.amount, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group row">
                <%= label_tag('expense[currency_attributes[name]]', 'Currency', class: 'col-xs-3 col-form-label mr-2') %>
                <div class="col-xs-9">
                  <% if action_name == 'new' || action_name == 'create' %>
                    <%= select_tag('expense[currency_attributes[name]]', options_for_select(Currency.names.to_a.map(&:first)), class: 'form-control currency-modal') %>
                  <% elsif action_name == 'edit' || action_name == 'update' %>
                    <% range = FiltersHelper::CurrencyNames.new(@expense.currency.name) %>
                    <%= select_tag('expense[currency_attributes[name]]', options_for_select(range.names), prompt: @expense.currency.name, class: 'form-control currency-modal') %>
                <% end %>
                </div>

                <% if @expense.errors[:currency].present? %>
                    <label for="calibration" class="col-xs-3 col-form-label mr-2 visibility-calibration">q</label>
                    <div class="col-xs-9">
                      <%= form.label :currency, @expense.errors[:currency].last, class: 'message', for: 'expense_currency_attributes_name' %>
                    </div>
                <% end %>
              </div>

              <div class="form-group row">
                <%= form.label t(:expense_type), class: 'col-xs-3 col-form-label mr-2' %>
                <div class="col-xs-9 clear_after_create">
                  <%= form.text_field :expense_type, class: 'form-control clear_after_create', id: 'expense_Rubric' %>
                </div>
              </div>
            </form>

          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= hidden_field_tag 'page', params[:page] %>
          <%= form.submit(class: 'btn btn-primary', id: 'modal-sub') %>
        </div>
      </div>
    </div>
  </div>


<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<script type="text/javascript" charset="utf-8">
  // assets/javascripts/application.js.erb
  var duration_start = "<%= @filter.first %>";
  var duration_end = "<%= @filter.last.to_date %>";
</script>

<div id="results"></div>

<div class="notice"></div>
<div id="myModal"></div>
<div class="print" id="print"></div>

  <%= link_to 'New Expense', new_expense_path(page: params[:page]), class: 'btn btn-success', remote: true %>
  <br><br>
  <%= form_tag('', method: :get, remote: true) do %>
    <label for="search" id="search_label">Expenses</label>
    <%= text_field_tag('', '', placeholder: t(:expenses_search), class: 'form-control mr-sm-2', id: 'search',
                       maxlength: Expense::MAX_LENGTH) %>
    <br>
<% end %>

<div class="row">

  <div class="col-lg-8">
  <table class="table table-striped" id="expenses">
    <thead class="thead-dark">
    <tr>
      <th><%= t(:expense_heading) %></th>
      <th><%= t(:expense_amount) %></th>
      <th><%= t(:expense_type) %></th>
      <th><%= t(:created_at) %></th>
      <th></th>
      <th>
        <%= link_to edit_user_expenses_sender_path(current_user), remote: true do %>
            <i class="fa fa-envelope printer" aria-hidden="true"></i>
      <% end %>
        <%= link_to print_user_expenses_print_path(current_user), id: 'click_me', remote: true do %>
          <i class="fa fa-print printer" aria-hidden="true"></i>
        <% end %>
      </th>
    </tr>
    </thead>

    <tbody id="search_list">
    <% @expenses.page(params[:page]).each do |expense| %>
        <tr id="<%= "col_#{ expense.id }" %>">
          <td><%= expense.name %></td>
          <td><%= expense.current_currency %></td>
          <td><%= expense.expense_type %></td>
          <td><%= expense.created_at.strftime('%d.%m.%Y') %></td>
          <td class="not-for-print"><%= link_to 'Edit', edit_expense_path(expense, page: params[:page], exp: {amount: expense.amount,
                                                                                         currency: expense.currency}),
                                                                                         class: 'btn btn-warning',
                                                                                         remote: true %>
          </td>
          <td class="not-for-print"><%= link_to 'Destroy', expense_path(expense, page: params[:page]), method: :delete,
                          class: 'btn btn-danger destroyer', remote: true %></td>
        </tr>
    <% end %>
        <tr class="js-calibration"></tr>
    </tbody>
  </table>
    <p id="total_sum">Total: <%= number_to_currency(current_user.currency_convert.total_amount,
                                                    unit: current_user.currency_convert.convert_currency,
                                                    delimiter: ' ', format: '%n %u') %>
    </p>
    <div id="pagination">
      <%= paginate @expenses.page(params[:page]), page: @expenses.page.current_page, theme: 'twitter-bootstrap-4', pagination_class: 'pagination-sm' %>
    </div>
  </div>

  <%= render 'filters/filter' %>
</div>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= form_for(@expense, local: true, remote: true, validate: true) do |form| %>
    <% if @expense.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

          <ul>
            <% @expense.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group row">
      <%= form.label :name, class: 'col-xs-3 col-form-label mr-2' %>
      <div class="col-xs-9">
        <%= form.text_field :name, class: 'form-control', maxlength: Expense::MAX_LENGTH, validate: { presence: true } %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :created_at, class: 'col-xs-3 col-form-label mr-2' %>
      <%= hidden_field_tag 'expense[created_at]' %>
      <div class="col-xs-9">
        <div id="expense_date" class="calendar form-control">
          <i class="fa fa-calendar"></i>&nbsp;
          <span id="date"></span> <i class="fa fa-caret-down"></i>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :amount, class: 'col-xs-3 col-form-label mr-2' %>
      <div class="col-xs-9">
        <%= form.text_field :amount, value: '%.2f' % @expense.amount, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= label_tag('expense[currency_attributes[name]]', 'Currency', class: 'col-xs-3 col-form-label mr-2') %>
      <div class="col-xs-9">
        <% if action_name == 'new' %>
            <%= select_tag('expense[currency_attributes[name]]', options_for_select(Currency.names.to_a.map(&:first)), class: 'form-control currency-modal') %>
        <% elsif action_name == 'edit' %>
            <% range = FiltersHelper::CurrencyNames.new(@expense.currency.name) %>
            <%= select_tag('expense[currency_attributes[name]]', options_for_select(range.names), prompt: @expense.currency.name, class: 'form-control') %>
        <% end %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :expense_type, class: 'col-xs-3 col-form-label mr-2' %>
      <div class="col-xs-9 clear_after_create">
        <%= form.text_field :expense_type, class: 'form-control clear_after_create' %>
      </div>
    </div>
    <%= hidden_field_tag 'page', params[:page] %>
    <%= form.submit(class: 'btn btn-primary', id: 'modal-sub') %>
<% end %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>